-- MySQL Script generated by MySQL Workbench
-- Wed May 26 16:56:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`user_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_1` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `userType` TINYINT NULL,
  `username` VARCHAR(15) NULL,
  `isProfessor` TINYINT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`likes` (
  `idlikes` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idlikes`, `users_idusers`),
  INDEX `fk_likes_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gadgets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gadgets` (
  `gadgetID` INT NOT NULL,
  `gadgetName` VARCHAR(45) NULL,
  `tags` VARCHAR(45) NULL,
  `class` VARCHAR(45) NULL,
  `likes_idlikes` INT NOT NULL,
  `likes_users_idusers` INT NOT NULL,
  PRIMARY KEY (`gadgetID`, `likes_idlikes`, `likes_users_idusers`),
  INDEX `fk_gadgets_likes1_idx` (`likes_idlikes` ASC, `likes_users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_gadgets_likes1`
    FOREIGN KEY (`likes_idlikes` , `likes_users_idusers`)
    REFERENCES `mydb`.`likes` (`idlikes` , `users_idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `idcomment` INT NOT NULL,
  `commentText` VARCHAR(45) NULL,
  `users_idusers` INT NOT NULL,
  `gadgets_gadgetID` INT NOT NULL,
  PRIMARY KEY (`idcomment`, `gadgets_gadgetID`),
  INDEX `fk_comments_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_comments_gadgets1_idx` (`gadgets_gadgetID` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_gadgets1`
    FOREIGN KEY (`gadgets_gadgetID`)
    REFERENCES `mydb`.`gadgets` (`gadgetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tags` (
  `idtags` INT NOT NULL,
  `tagtext` VARCHAR(45) NULL,
  `users_idusers` INT NOT NULL,
  `gadgets_gadgetID` INT NOT NULL,
  PRIMARY KEY (`idtags`, `users_idusers`),
  INDEX `fk_tags_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_tags_gadgets1_idx` (`gadgets_gadgetID` ASC) VISIBLE,
  CONSTRAINT `fk_tags_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_gadgets1`
    FOREIGN KEY (`gadgets_gadgetID`)
    REFERENCES `mydb`.`gadgets` (`gadgetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
